### ISSUE TITLE
Please do use github.com/valyala/fasthttp.

### ISSUE THREAD

**Issue by zypeh** [si3nloong/raptor#15]
```toml
# This fork has been deprecated.
[[constraint]]
  branch = "master"
  name = "github.com/erikdubbelboer/fasthttp" 

# And this fork is using the deprecated fasthttp fork above.
[[constraint]]
  name = "github.com/thehowl/fasthttprouter" 
  version = "0.2.1"
```

I do suggest using `github.com/valyala/fasthttp` for better support and updates. As I see there is no strong reason to use the fasthttprouter also.

Instead will introduce unsound problem/compatibility problem for later go versions. *1

1. [Using unsafe pointer to avoid []byte to string conversion in thehowl/fasthttprouter](https://github.com/buaazp/fasthttprouter/commit/0e77ecfde28ad422d670671c17415e1d15f0f5be)
